### ISSUE TITLE
Continue development

### ISSUE THREAD

**Issue by lazyfrosch** [NETWAYS/traefik-provider-openstack#2]
Please check branch `wip` for a some dev changes

**Comment by pdorschner** [comment]
I wanted to continue the development of this project, but I'm overwhelmed of the complexity of it. 
Is there some documentation how I can test it? If I'm using `docker-compose up` and start the `main.go`, I can't reach Traefik at all. Or is there a complete different approach?
What was the idea of the `Dockerfile`, `docker-compose` and the whole `main.go`?

Would be a great help :)

Best regards,
Philipp

**Comment by lazyfrosch** [comment]
@pdorschner This is an API provider for Traefik to collect configuration like routers, services, middleware and such.

See:
- https://github.com/NETWAYS/traefik-provider-openstack/blob/main/examples/traefik.yml
- https://doc.traefik.io/traefik/providers/overview/
- https://doc.traefik.io/traefik/providers/http/

**Comment by martialblog** [comment]
Currently not maintained anymore.
